---
- name: Configure Cisco Router using cisco.ios collection
  hosts: cisco_router
  gather_facts: yes
  connection: ssh

  tasks:
    - name: Configure the login banner
      cisco.ios.ios_banner:
        banner: login
        text: "This is login banner."
        state: present
      
    - name: Configure the exec banner
      cisco.ios.ios_banner:
        banner: exec
        text: "This is exec banner."
        state: present

    - name: Configure the motd banner
      cisco.ios.ios_banner:
        banner: motd
        text: "This is motd banner."
        state: present
    
    - name: Configure Interface Meta
      cisco.ios.ios_interfaces:
        config:
          - name: GigabitEthernet0/1
            description: Connection to VLAN 10
            enabled: true
          - name: GigabitEthernet0/2
            description: Connection to VLAN 20
            enabled: true
        state: merged

    - name: Configure Interface L3 IPv6
      cisco.ios.ios_l3_interfaces:
        config:
          - name: GigabitEthernet0/1
            ipv6:
              - address: 2001:db8:1:3::/64
          - name: GigabitEthernet0/2
            ipv6:
              - address: 2001:db8:2:4::/64
        state: merged

    - name: Configure Interface L2 VLAN
      cisco.ios.ios_l2_interfaces:
        config:
          - name: GigabitEthernet0/1
            mode: access
            access:
              vlan: 10
          - name: GigabitEthernet0/2
            mode: trunk
            trunk:
              allowed_vlans: 10-20,40
              native_vlan: 40
              #pruning_vlans: 10,20
              encapsulation: dot1q
        state: merged