---
- name: Configure Cisco Router using cisco.ios collection
  hosts: cisco_router
  gather_facts: yes
  connection: ssh

  tasks:
    - name: Configure IPv6 and VLANs on two interfaces
      cisco.ios.ios_interfaces:
        config:
          - name: GigabitEthernet0/1
            description: Connection to VLAN 10
            enabled: true
            mode: layer3
          - name: GigabitEthernet0/2
            description: Connection to VLAN 20
            enabled: true
            mode: layer3
        state: merged