---
- name: Configure Cisco Router using cisco.ios collection
  hosts: cisco_router
  gather_facts: yes
  connection: ssh

  tasks:
    - name: Configure Interface Meta
      cisco.ios.ios_interfaces:
        config:
          - name: GigabitEthernet0/1
            description: Connection to VLAN 10
            enabled: true
          - name: GigabitEthernet0/2
            description: Connection to VLAN 20
            enabled: true
        state: merged
    - name: Merge provided configuration with device configuration
      cisco.ios.ios_l3_interfaces:
        config:
          - name: GigabitEthernet0/1
            ipv6:
              - address: 2001:db8:0:3::/64
          - name: GigabitEthernet0/2
            ipv6:
              - address: 2001:db8:0:3::/64
        state: merged